version: "2.2"
services:

  backdevopsimage:
    image: "nassimbenali/backdevopsimage:1.0"
    build: ./
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/devops?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - mysql
    volumes:
      - .m2:/root/.m2


  mysql:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=devops
    ports:
      - "3307:3306"